server:
  port: 9000
spring:
  application:
    name: cards
  profiles:
    active: default
#  cloud:
#    config:
#      uri: http://configserver:8071
  config:
    import: optional:configserver:http://localhost:8071
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: 'update'
#    defer-datasource-initialization: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    show-sql: 'true'
  h2:
    console:
      enabled: true

endpoints:
  shutdown:
    enable: true

management:
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - refresh
          - shutdown

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl.defaultZone: http://localhost:8070/eureka

info:
  app:
    name: Cards Microservice
    description: Bank Card App
    version: 1.0.0