spring:
  application:
    name: gateway-server
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411/
  #    sender:
  #      type: rabbit
  #    rabbitmq:
  #      queue: zipkin
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Gateway Server Microservice
    description: Bank Gateway Server App
    version: 1.0.0

logging.level.com.tworuszka.gateway-server: DEBUG