spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8071
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Gateway Server Microservice
    description: Bank Gateway Server App
    version: 1.0.0

logging.level.com.tworuszka.gateway-server: DEBUG