server:
  port: 8071

encrypt:
  key: fnadkjshipv353u-8q9fn994t

spring:
  application:
    name: configserver
  profiles:
#    active: native
    active: git

  cloud.config.server:
#    native.search-locations: classpath:/config
    git:
      uri: https://github.com/michaltworuszka/bankapp-config.git
      clone-on-start: true
      default-label: main