version: "3.8"

services:
  accounts:
    image: misiekfiol/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - bank-network

  loans:
    image: misiekfiol/loans:latest
    ports:
      - "8090:8090"
    networks:
      - bank-network

  cards:
    image: misiekfiol/cards:latest
    ports:
      - "9000:9000"
    networks:
      - bank-network

networks:
  bank-network: