server:
  port: 8090
spring:
  application:
    name: loans
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411/
  #    sender:
  #      type: rabbit
  #    rabbitmq:
  #      queue: zipkin
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8071
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: 'update'
#    defer-datasource-initialization: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: 'true'
    show-sql: 'true'
  h2:
    console:
      enabled: true

endpoints:
  shutdown:
    enable: true

management:
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl.defaultZone: http://localhost:8070/eureka

info:
  app:
    name: Loans Microservice
    description: Bank Loan App
    version: 1.0.0