server:
  port: 8071

encrypt:
  key: fnadkjshipv353u-8q9fn994t

spring:
  application:
    name: configserver
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411/
  #    sender:
  #      type: rabbit
  #    rabbitmq:
  #      queue: zipkin
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  profiles:
    #    active: native
    active: git
  cloud.config.server:
    #    native.search-locations: classpath:/config
    git:
      uri: https://github.com/michaltworuszka/bankapp-config.git
      clone-on-start: true
      default-label: main