version: "3.8"

services:

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - bank-network
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bank-network

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - bank-network

  configserver:
    image: misiekfiol/configserver:latest
    ports:
      - "8071:8071"
    depends_on:
      - zipkin
    networks:
      - bank-network
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411

  eureka-server:
    image: misiekfiol/eureka-server
    ports:
      - "8070:8070"
    networks:
      - bank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411

  accounts:
    image: misiekfiol/accounts:latest
    ports:
      - "8080:8080"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411

  loans:
    image: misiekfiol/loans:latest
    ports:
      - "8090:8090"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411

  cards:
    image: misiekfiol/cards:latest
    ports:
      - "9000:9000"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411

  gateway-server:
    image: misiekfiol/gateway-server:latest
    ports:
      - "8072:8072"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eureka-server
      - cards
      - accounts
      - loans
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 5
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411

networks:
  bank-network: