spring:
  application:
    name: eureka-server
  sleuth:
    sampler:
      percentage: 1
  zipkin:
    base-url: http://localhost:9411/
  #    sender:
  #      type: rabbit
  #    rabbitmq:
  #      queue: zipkin
  #  rabbitmq:
  #    host: localhost
  #    port: 5672
  #    username: guest
  #    password: guest
  config:
    import: optional:configserver:http://localhost:8071